package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

var completionScripts = map[string]string{
	"bash": `# Generated by bibleit completion bash. Source this file in Bash.
_bibleit_complete() {
    COMPREPLY=()
    local candidate
    while IFS= read -r candidate; do
        [[ -n "$candidate" ]] && COMPREPLY+=("$candidate")
    done < <("${COMP_WORDS[0]}" __complete "${COMP_WORDS[@]:1:COMP_CWORD}")
}
complete -F _bibleit_complete bibleit
`,
	"zsh": `#compdef bibleit
# Generated by bibleit completion zsh. Source after compinit, or install as _bibleit.
_bibleit() {
    local -a candidates
    candidates=("${(@f)$("${words[1]}" __complete "${words[@]:1:$((CURRENT-1))}")}")
    [[ -n "${candidates[1]}" ]] && compadd -- "${candidates[@]}"
}
if [[ ${funcstack[1]} == _bibleit ]]; then
    _bibleit "$@"
else
    compdef _bibleit bibleit
fi
`,
	"fish": `# Generated by bibleit completion fish.
function __bibleit_candidates
    set -l words (commandline -opc)
    set -l current (commandline -ct)
    command $words[1] __complete $words[2..-1] "$current"
end
complete -c bibleit -f -a '(__bibleit_candidates)'
`,
}

func completionCommand(args []string, format string) int {
	if len(args) != 1 {
		return fail(exitUsage, "usage: bibleit completion bash|zsh|fish")
	}
	script, exists := completionScripts[args[0]]
	if !exists {
		return fail(exitUsage, "unsupported shell %q (use bash, zsh, or fish)", args[0])
	}
	if format != "table" && format != "raw" {
		return fail(exitUsage, "completion scripts require table or raw output")
	}
	if _, err := fmt.Fprint(os.Stdout, script); err != nil {
		return outputError(exitFailure, err)
	}
	return exitOK
}

// The final word is the current prefix, including an explicit empty word.
// Only local profile names are dynamic. Never query a server or emit credentials.
func completeCommand(words []string) int {
	for _, candidate := range completionCandidates(words) {
		fmt.Println(candidate)
	}
	return exitOK
}
func completionCandidates(words []string) []string {
	if len(words) == 0 {
		words = []string{""}
	}
	prefix := words[len(words)-1]
	previous := words[:len(words)-1]
	valueOptions := map[string]bool{"--profile": true, "--format": true, "--identity": true, "--transport": true, "--endpoint": true}
	optionValues := func(option string) []string {
		switch option {
		case "--format":
			return []string{"table", "raw", "json", "ndjson"}
		case "--transport":
			return []string{"http", "ssh"}
		case "--profile":
			return completionProfileNames()
		}
		return nil
	}
	filter := func(candidates []string, match, prepend string) []string {
		result := []string{}
		for _, candidate := range candidates {
			if strings.HasPrefix(candidate, match) {
				result = append(result, prepend+candidate)
			}
		}
		sort.Strings(result)
		return result
	}
	args := []string{}
	used := map[string]bool{}
	literal := false
	for i := 0; i < len(previous); i++ {
		word := previous[i]
		if word == "--" && !literal {
			literal = true
			continue
		}
		name, _, inline := strings.Cut(word, "=")
		if !literal && valueOptions[name] {
			used[name] = true
			if !inline {
				if i == len(previous)-1 {
					return filter(optionValues(name), prefix, "")
				}
				i++
			}
		} else if !literal && word == "--yes" {
			used[word] = true
		} else {
			args = append(args, word)
		}
	}
	if !literal && strings.HasPrefix(prefix, "-") {
		if name, value, inline := strings.Cut(prefix, "="); inline {
			return filter(optionValues(name), value, name+"=")
		}
		options := []string{}
		for _, option := range []string{"--profile", "--format", "--identity", "--yes", "--help"} {
			if !used[option] {
				options = append(options, option)
			}
		}
		if len(args) >= 2 && args[0] == "profile" && args[1] == "add" {
			for _, option := range []string{"--endpoint", "--transport"} {
				if !used[option] {
					options = append(options, option)
				}
			}
		}
		return filter(options, prefix, "")
	}
	candidates := []string{}
	if len(args) == 0 {
		candidates = []string{"ping", "server", "account", "auth", "profile", "translation", "read", "search", "live", "completion", "help", "version"}
	} else {
		switch args[0] {
		case "help":
			if len(args) == 1 {
				candidates = []string{"server", "account", "auth", "profile", "translation", "read", "search", "live", "completion"}
			}
		case "completion":
			if len(args) == 1 {
				candidates = []string{"bash", "zsh", "fish"}
			}
		case "auth":
			if len(args) == 1 {
				candidates = []string{"login", "logout", "info", "whoami"}
			}
			if len(args) == 2 && args[1] == "login" {
				candidates = []string{"ssh"}
			}
		case "server":
			if len(args) == 1 {
				candidates = []string{"info", "help"}
			}
			if len(args) == 2 && args[1] == "help" {
				candidates = []string{"server", "account", "auth", "translation", "live"}
			}
		case "account":
			if len(args) == 1 {
				candidates = []string{"info", "quotas", "tokens"}
			}
		case "translation":
			if len(args) == 1 {
				candidates = []string{"list", "add", "remove", "info", "catalog"}
			}
		case "profile":
			if len(args) == 1 {
				candidates = []string{"add", "use", "list", "show", "remove"}
			}
			if len(args) == 2 && oneOf(args[1], "use", "show", "remove") {
				candidates = completionProfileNames()
			}
		case "live":
			if len(args) == 1 {
				candidates = []string{"list", "create", "delete"}
			}
			if len(args) == 2 {
				if args[1] == "delete" {
					candidates = []string{"all"}
				} else if !oneOf(args[1], "list", "create") {
					candidates = []string{"info", "stats", "start", "stop", "pause", "resume", "delete", "subscribe", "clear", "secret", "set", "stack"}
				}
			}
			if len(args) == 3 && !oneOf(args[1], "list", "create", "delete") {
				switch args[2] {
				case "secret":
					candidates = []string{"create", "rotate", "delete"}
				case "set":
					candidates = []string{"name", "reference", "translations"}
				case "stack":
					candidates = []string{"info", "clear", "push", "pop"}
				}
			}
		}
	}
	return filter(candidates, prefix, "")
}
func completionProfileNames() []string {
	store, _, err := loadStore()
	if err != nil {
		return nil
	}
	names := []string{}
	for name := range store.Profiles {
		names = append(names, name)
	}
	return names
}
