"""Framework-free operator application API.

The exports at this path preserve the import used by the unmerged operator
prototype. New integrations should construct :class:`OperatorService` and use
typed commands from ``bibleit.operator.models``.
"""

from bibleit.operator.errors import CapabilityError, CommandValidationError, OperatorError, PublishError
from bibleit.operator.models import (
    ChapterEnd,
    ChapterStart,
    CloseTranslation,
    Goto,
    GotoReference,
    InstallEvent,
    NextChapter,
    NextVerse,
    OpenTranslation,
    OperatorCommand,
    OperatorEvent,
    OperatorState,
    PreviousChapter,
    PreviousVerse,
    Reference,
    ResolveResult,
    SearchResult,
    SetActive,
    SetLive,
    SetStrongs,
    StateEvent,
    TranslationCatalogState,
    TranslationInfo,
    TranslationLanguage,
    VerseColumn,
    VerseRow,
    VerseWindow,
    parse_command,
)
from bibleit.operator.ports import ConfigStore, PublishTarget, ReadingService, TaskSpawner, TranslationCatalog
from bibleit.operator.service import (
    AsyncioTaskSpawner,
    CoreReadingService,
    NativeTranslationCatalog,
    OperatorCapabilities,
    OperatorService,
)
from bibleit.operator.session import (
    DEFAULT_BEFORE,
    DEFAULT_TOTAL,
    MAX_TOTAL,
    EventSubscription,
    HubTarget,
    OperatorSession,
    RelayTarget,
)

__all__ = [
    "AsyncioTaskSpawner",
    "CapabilityError",
    "CommandValidationError",
    "ConfigStore",
    "CoreReadingService",
    "DEFAULT_BEFORE",
    "DEFAULT_TOTAL",
    "EventSubscription",
    "HubTarget",
    "InstallEvent",
    "MAX_TOTAL",
    "NativeTranslationCatalog",
    "OperatorCapabilities",
    "OperatorCommand",
    "OperatorError",
    "OperatorEvent",
    "OperatorService",
    "OperatorSession",
    "OperatorState",
    "PublishError",
    "PublishTarget",
    "ReadingService",
    "RelayTarget",
    "ResolveResult",
    "SearchResult",
    "StateEvent",
    "TaskSpawner",
    "TranslationCatalog",
    "TranslationCatalogState",
    "TranslationInfo",
    "TranslationLanguage",
    "VerseColumn",
    "VerseRow",
    "VerseWindow",
    "parse_command",
    "ChapterEnd",
    "ChapterStart",
    "CloseTranslation",
    "Goto",
    "GotoReference",
    "NextChapter",
    "NextVerse",
    "OpenTranslation",
    "PreviousChapter",
    "PreviousVerse",
    "Reference",
    "SetActive",
    "SetLive",
    "SetStrongs",
]
