from __future__ import annotations

from collections.abc import Awaitable, Callable, Sequence
from typing import Any, Protocol

from bibleit import reader, translation
from bibleit.operator.models import ResolveResult, SearchResult, TranslationCatalogState, VerseRow


class OpenedTranslation(reader.ReadableTranslation, Protocol):
    @property
    def strongs(self) -> dict[str, translation.StrongEntry]: ...
    def close(self) -> Any: ...


class PublishTarget(Protocol):
    name: str

    async def publish(self, payload: dict) -> None: ...
    async def set_live(self, live: bool) -> None: ...


class TranslationCatalog(Protocol):
    async def list(self) -> TranslationCatalogState: ...
    async def open(self, slug: str) -> OpenedTranslation: ...
    async def install(self, slug: str) -> None: ...
    async def remove(self, slug: str) -> None: ...


class ReadingService(Protocol):
    def books(self, opened: OpenedTranslation) -> Sequence[reader.Book]: ...

    def window(
        self,
        opened: OpenedTranslation,
        ref: translation.TranslationRef,
        *,
        before: int,
        total: int,
    ) -> reader.VerseWindow: ...
    def row(self, opened: OpenedTranslation, line: str) -> VerseRow | None: ...
    def resolve(self, opened: OpenedTranslation, value: str, state: Any) -> ResolveResult: ...
    async def search(self, opened: OpenedTranslation, query: str, *, limit: int) -> Sequence[SearchResult]: ...
    async def strongs(self, opened: OpenedTranslation, code: str) -> translation.StrongEntry | None: ...


class ConfigStore(Protocol):
    async def read(self) -> dict[str, str]: ...
    async def write(self, values: dict[str, str]) -> None: ...


class TaskSpawner(Protocol):
    def spawn(self, awaitable: Awaitable[Any]) -> Any: ...
    async def close(self) -> None: ...


TranslationOpener = Callable[[str], Awaitable[OpenedTranslation]]
