[project]
name = "bibleit"
version = "0.4.0"
authors = [{ name = "Felipe Mamud", email = "trovatti@gmail.com" }]
description = "Interactive Bible Reading"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "aiohttp",
  "gnureadline; platform_system == 'Darwin'",
  "rapidfuzz",
  "requests",
  "textual",
  "unidecode",
]

[project.scripts]
bibleit = "bibleit.cli:main"

[project.optional-dependencies]
dev = ["black", "flake8", "textual-dev"]

[project.urls]
"Homepage" = "https://github.com/fmamud/bibleit"
"Bug Tracker" = "https://github.com/fmamud/bibleit/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.envs.default]
python = "3.11"

[tool.hatch.build.targets.wheel]
packages = ["src/bibleit"]

[tool.hatch.build.targets.sdist.force-include]
"../libbibleit/Makefile" = "native/libbibleit/Makefile"
"../libbibleit/README.md" = "native/libbibleit/README.md"
"../libbibleit/include" = "native/libbibleit/include"
"../libbibleit/src" = "native/libbibleit/src"

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"

[tool.black]
line-length = 120
target-version = ["py311"]
