-module(bibleit_server_sup).
-behaviour(supervisor).
-export([start_link/0, init/1]).

start_link() -> supervisor:start_link({local, ?MODULE}, ?MODULE, []).

init([]) ->
    Translations = #{id => bibleit_translation_registry,
                     start => {bibleit_translation_registry, start_link, []},
                     restart => permanent, shutdown => 5000,
                     type => worker, modules => [bibleit_translation_registry]},
    Authorization = #{id => bibleit_authorization,
                      start => {bibleit_authorization, start_link, []}, restart => permanent, shutdown => 5000,
                      type => worker, modules => [bibleit_authorization]},
    HttpSessions = #{id => bibleit_http_session,
                     start => {bibleit_http_session, start_link, []}, restart => permanent, shutdown => 5000,
                     type => worker, modules => [bibleit_http_session]},
    HttpOauth = #{id => bibleit_http_oauth,
                  start => {bibleit_http_oauth, start_link, []}, restart => permanent, shutdown => 5000,
                  type => worker, modules => [bibleit_http_oauth]},
    EmailAccounts = #{id => bibleit_email_account,
                      start => {bibleit_email_account, start_link, []}, restart => permanent, shutdown => 5000,
                      type => worker, modules => [bibleit_email_account]},
    AvailableTranslations = #{id => bibleit_translation_available,
                              start => {bibleit_translation_available, start_link, []},
                              restart => permanent, shutdown => 5000,
                              type => worker, modules => [bibleit_translation_available]},
    Store = #{id => bibleit_live_store,
              start => {bibleit_live_store, start_link, []},
              restart => permanent, shutdown => 5000,
              type => worker, modules => [bibleit_live_store]},
    Sessions = #{id => bibleit_live_session_sup,
                 start => {bibleit_live_session_sup, start_link, []},
                 restart => permanent, shutdown => 5000,
                 type => supervisor, modules => [bibleit_live_session_sup]},
    Registry = #{id => bibleit_live_registry,
                 start => {bibleit_live_registry, start_link, []},
                 restart => permanent, shutdown => 5000,
                 type => worker, modules => [bibleit_live_registry]},
    Connections = #{id => bibleit_tcp_connection_sup,
                    start => {bibleit_tcp_connection_sup, start_link, []},
                    restart => permanent, shutdown => 5000,
                    type => supervisor, modules => [bibleit_tcp_connection_sup]},
    RateLimiter = #{id => bibleit_rate_limiter,
                    start => {bibleit_rate_limiter, start_link, []},
                    restart => permanent, shutdown => 5000,
                    type => worker, modules => [bibleit_rate_limiter]},
    Listener = #{id => bibleit_tcp_listener,
                 start => {bibleit_tcp_listener, start_link, []},
                 restart => permanent, shutdown => 5000,
                 type => worker, modules => [bibleit_tcp_listener]},
    TlsListener = #{id => bibleit_tls_listener,
                    start => {bibleit_tls_listener, start_link, []},
                    restart => permanent, shutdown => 5000,
                    type => worker, modules => [bibleit_tls_listener]},
    SshListener = #{id => bibleit_ssh_listener,
                    start => {bibleit_ssh_listener, start_link, []}, restart => permanent, shutdown => 5000,
                    type => worker, modules => [bibleit_ssh_listener]},
    SshIdentity = #{id => bibleit_ssh_identity,
                    start => {bibleit_ssh_identity, start_link, []}, restart => permanent, shutdown => 5000,
                    type => worker, modules => [bibleit_ssh_identity]},
    HttpListener = #{id => bibleit_http_listener,
                     start => {bibleit_http_listener, start_link, []},
                     restart => permanent, shutdown => 5000,
                     type => worker, modules => [bibleit_http_listener]},
    {ok, {{one_for_one, 5, 10}, [Authorization, HttpSessions, HttpOauth, EmailAccounts, AvailableTranslations, Translations, Store, Sessions, Registry, Connections, RateLimiter, Listener, TlsListener, SshIdentity, SshListener, HttpListener]}}.
